### ISSUE TITLE
merge DB files at the end of second phase of the workflow 

### ISSUE THREAD

**Issue by DininduSenanayake** [nesi/APSIM-HPC#66]

**Comment by DininduSenanayake** [comment]
I thought we can use built in function `--merge-db-files` to do this but not quite sure how to specify the .db files 

* It doesn't respond to wild cards

```bash
❯ apptainer exec ../../../container/apsim-2024.09.7579.0.aimg Models --merge-db-files *.db
System.ArgumentException: No files were specified
   at Models.Program.Run(Options options) in /tmp/ApsimX/Models/Main.cs:line 112
```
* No responde to a comma separated list nor separated by space
```bash
❯ apptainer exec ../../../container/apsim-2024.09.7579.0.aimg Models --merge-db-files 13223_Ahuriri_7a1.db,13223_Bushstream_3b1.db
System.ArgumentException: No files were specified
   at Models.Program.Run(Options options) in /tmp/ApsimX/Models/Main.cs:line 112
```
```bash
❯ apptainer exec ../../../container/apsim-2024.09.7579.0.aimg Models --merge-db-files 13223_Ahuriri_7a1.db 13223_Bushstream_3b1.db
System.ArgumentException: No files were specified
   at Models.Program.Run(Options options) in /tmp/ApsimX/Models/Main.cs:line 112
```
* Then I just gave the path to .db files ( current working directory) 
```bash
❯ apptainer exec ../../../container/apsim-2024.09.7579.0.aimg Models --merge-db-files ./
System.ArgumentException: No files were specified
   at Models.Program.Run(Options options) in /tmp/ApsimX/Models/Main.cs:line 112
```

@Ollehar can you ask one of the developers how to assign filenames to this function ?

**Comment by DininduSenanayake** [comment]
for the moment, we will not to do this as it is better to leave them separately which simplifies the process of merge
